Replaced the images of the three service boxes
unboxed/ubxd_web_refresh pull request #353
Opened 2017-07-18 10:22 UTC by DennisTsiang

Replaced the images of the three service boxes with newer versions

2017-07-19 17:36 UTC, NeilvB commented
I think we can compress these jpgs to improve the page load time. I used the Google PageSpeed service on this (e.g. https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdeploy-preview-353--unboxed-co-production.netlify.com%2F)

I've been using the [ImageOptim](https://imageoptim.com/mac) app to compress jpgs at 85% in most cases, which seems to improve our score.

2017-07-19 17:41 UTC, neilvanbeinum requested changes
Mostly looks good! 👍  The trello card design screenshot shows square images - do we want to crop these images?

Please also see the note about image compression above.

2017-07-21 08:38 UTC, h-lame commented
It might be a fun project to see if we can make the middleman build step apply jpeg and png compression automatically so we don't have to remember.

2017-07-21 09:21 UTC, neilvanbeinum approved these changes

2017-07-21 09:23 UTC, merged