Displays 'No current vacancies' if no job roles listed
unboxed/ubxd_web_refresh pull request #364
Opened 2017-07-26 13:18 UTC by DennisTsiang

If roles is nil then it displays 'No current vacancies' as the title, with the text "We don't currently have any team openings" underneath.

2017-07-26 15:51 UTC, neilvanbeinum requested changes
Mostly looks good!

I noticed that at mobile widths there's no margin between this section and the next. I think a margin-bottom on the paragraph element for these widths should do the trick.

2017-07-26 15:51 UTC, NeilvB commented on source/assets/stylesheets/styles/_jobs_page_tile.scss
> +.jobs-page-tile-no-roles__paragraph {
We should stick to the block name in the file for this rule (or make a new file for the new block). How do you feel about `.jobs-page-tile__no-roles-paragraph`?

2017-07-26 16:21 UTC, DennisTsiang commented
Amended those changes and squashed them to the previous commit

2017-07-26 16:24 UTC, NeilvB commented on source/jobs.erb
> +#      image: /assets/images/jobs/designer.jpg
We'll need to uncomment these :)

2017-07-27 08:26 UTC, DennisTsiang commented on source/jobs.erb
> +#      image: /assets/images/jobs/designer.jpg
Ah sorry, I left that in during testing

2017-07-27 09:42 UTC, neilvanbeinum approved these changes

2017-07-27 09:43 UTC, NeilvB commented
Thanks for taking the time to do the class rename! I think that's an improvement 👍

2017-07-27 13:35 UTC, merged