Image standards
unboxed/ubxd_web_refresh pull request #388
Opened 2017-08-14 11:31 UTC by DennisTsiang

Fixes style guide images and links. Also adds some image guidelines to the README.

2017-08-14 13:08 UTC, NeilvB commented on README.md
> +retina version should be twice the size of the non-retina version.
We should probably point people at the style guide here so they have a reference for the image dimensions.

2017-08-14 13:25 UTC, NeilvB commented
Thanks for updating this @DennisTsiang.

Couple of things that I think we need to update on the style guide:

- The style guide images from placehold.it currently are not showing on the preview URL due to a mixed content error. Updating these to `https` should fix it.
- It's something that should have arguably been done at the time, but I think the style guide would benefit from having some additional elements in it so that devs and e.g. product owners can refer to it for all of the image dimensions that we use on our site (excluding the blog which I don't think has rules at the moment). For instance: `.product-story-large-tile`, `.product-story-small-tile`, `.person-tile`, as well as a quote block with an image and maybe others too. Hopefully mostly a copy-paste job and double checking the correct image dimensions to pass to placehold.it

2017-08-15 08:43 UTC, neilvanbeinum requested changes

2017-08-15 08:43 UTC, NeilvB commented on source/style-guide.erb
> +          image: "http://via.placeholder.com/150x254"
We get mixed content warnings for these when viewing the preview site. Can we change them to `https`? (Same for the others below)

2017-08-15 08:43 UTC, NeilvB commented on source/style-guide.erb
> +              <img class="person-tile__image" src="/assets/images/people/tom-sabin.png" alt="tom sabin" />
I wonder if we should also use a placeholder image with dimensions here too. I think it should help when people add new caricatures to use the correct size.

2017-08-15 09:00 UTC, DennisTsiang commented on source/style-guide.erb
> +          image: "http://via.placeholder.com/150x254"
Apologies, I don't know how I missed those. I have amended them in the commit.

2017-08-15 09:00 UTC, DennisTsiang commented on source/style-guide.erb
> +              <img class="person-tile__image" src="/assets/images/people/tom-sabin.png" alt="tom sabin" />
Good idea, will change that to show the placeholder.

2017-08-15 13:33 UTC, neilvanbeinum approved these changes
Looks good! Thanks for the updates. One last thing I wondered was whether we want to group together the "blocks" - so for instance, we could add the whitepaper section above the typography section so its in the same place as the other blocks. I don't feel super strongly about it though.

2017-08-18 15:17 UTC, merged