Align tile widths
unboxed/ubxd_web_refresh pull request #389
Opened 2017-08-17 09:48 UTC by DennisTsiang

Aligned tile widths so that they are all consistent on the site, and give them a padding on either side.

2017-08-17 15:33 UTC, neilvanbeinum requested changes
Left a couple of very minor comments. Overall I think it looks good. As we discussed in person, I think the product story tiles at tablet width might need to kept more consistent with the existing design.

2017-08-17 15:33 UTC, NeilvB commented on source/people.erb
> +    <% data.people.each do |person| %>
I don't think this needs indenting

2017-08-17 15:33 UTC, NeilvB commented on source/assets/stylesheets/styles/_homepage_tile.scss
> +
Extra line ✂️  :)

2017-08-17 16:07 UTC, DennisTsiang commented on source/assets/stylesheets/styles/_homepage_tile.scss
> +
That file gets changed in a later commit (a1aa1f3)

2017-08-21 13:35 UTC, neilvanbeinum requested changes

2017-08-21 13:35 UTC, NeilvB commented on source/assets/stylesheets/styles/_small_tile.scss
> +  width: 100%;ht: 190px;
The text after the first `;` looks like a typo that can be deleted

2017-08-21 13:35 UTC, NeilvB commented on source/product-stories.erb
> +          <div class="<%= class_name %>__paragraph"><%= product_story.title %></div>
Why did we rename this to `paragraph`? I agree that calling the content `title` isn't accurate, but paragraph is a bit generic to my mind. How about `description`? Whichever name we use I suggest that the class name and the key match in the same way as we've done for `client`.

2017-08-21 13:35 UTC, NeilvB commented on source/assets/stylesheets/styles/_roles_tile.scss
>    object-fit: cover;
It would be good to add a comment here saying why we've got this unusual rule

2017-08-21 14:34 UTC, DennisTsiang commented on source/assets/stylesheets/styles/_roles_tile.scss
>    object-fit: cover;
Good point, I'll add a comment explaining this in the commit

2017-08-22 08:52 UTC, NeilvB commented on source/assets/stylesheets/styles/_roles_tile.scss
>    object-fit: cover;
It's good we've got the description in the commit message but I also think a comment in the CSS file itself would be useful. A short one-liner should do it just explaining that the object fit JS library requires this rule to work.

2017-08-22 08:52 UTC, neilvanbeinum approved these changes

2017-08-22 09:04 UTC, DennisTsiang commented on source/assets/stylesheets/styles/_roles_tile.scss
>    object-fit: cover;
Added short comments to the object-fit property now

2017-08-22 14:59 UTC, merged